identity:
  appId: "myApp"
auth:
  key: "key"
  token: "token"
options:
  domain: "internetofthings.ibmcloud.com"
  logLevel: "INFO"
  mqtt:
    instanceId: "myInstance"
    port: "8883"
    transport: "tcp"
    cleanStart: "false"
    sessionExpiry: "3600"
    keepAlive: "60"
    caFile: "myPath"
  http:
    verify: true
